spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mail:
    host: smtp.gmail.com
    port: 587
    username: stj960215@gmail.com
    password: umwzfnfdeyoqnqnb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/BlackLizard?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.stj.tunnel.blacklizard.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  siteName: 검은도마뱀
  siteUri: http://localhost:8085
  siteMainUri: http://localhost:8085/usr/home/main
  siteLoginUri: http://localhost:8085/usr/member/login
  emailFrom: no-reply@localhost
  emailFromName: 검은도마뱀
  logging:
    dir: log
    level: info

---

spring:
  profiles: local
server:
  port: 8085
